---
- name: Create PBS Nginx File
  ansible.builtin.copy:
    src: files/nginx-site-pbs
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: '0644'
    directory_mode: '0755'
  notify: restart nginx
