---
- block:
  - name: Create Network Interfaces file
    ansible.builtin.template:
      src: templates/interfaces.j2
      dest: /etc/network/interfaces
      owner: root
      group: root
      mode: '0644'
      trim_blocks: true
      lstrip_blocks: true
    notify:
      - networking_restart

  tags:
    - pve-network
