---
#
- name: Check if swap file exists
  stat:
    path: "{{ swap_file }}"
  register: swap_file_check

- name: Create swap file
  command: fallocate -l {{ swap_size }} {{ swap_file }}
  when: not swap_file_check.stat.exists

- name: Set permissions on swap file
  file:
    path: "{{ swap_file }}"
    mode: 0600

- name: Format swap file
  command: mkswap {{ swap_file }}
  when: not swap_file_check.stat.exists

- name: Add to fstab
  lineinfile:
    dest: /etc/fstab
    regexp: "{{ swap_file }}"
    line: "{{ swap_file }} none swap sw 0 0"
  notify: enable swap

- name: Set swapiness
  sysctl:
    name: vm.swappiness
    value: "1"
