---
- name: Include PBS (Proxmox Backup Server) General Setup Tasks
  ansible.builtin.include_tasks: pbs.yml
  args:
    apply:
      become: true
  when: PBS
  tags: 
    - pbs-general

- name: Include PBS (Proxmox Backup Server) Signed TLS Tasks
  ansible.builtin.include_tasks: pbs-tls.yml
  args:
    apply:
      become: true
  when: PBS
  tags: 
    - pbs-tls
