---
- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: restart pveproxy
  ansible.builtin.command:
    cmd: pveproxy restart