---
- name: Include Docker Install Tasks
  ansible.builtin.include_tasks: docker.yml
  args:
    apply:
      become: true
  when:
    - not PVE and
      ( DOCKER|bool )

- name: Include Komodo Install Tasks
  ansible.builtin.include_tasks: komodo.yml
  args:
    apply:
      become: true
  when:
    - not PVE and
      ( DOCKER|bool ) and
      ( KOMODO|bool )
