all:
localhosts:
  hosts:
    ubuntu:
      ansible_host: 127.0.0.1

      ntp_service: "chrony"

      FIREWALL: true
      firewall_service: "ufw"

      SWAP: true
      swap_size: "512M"
      swap_file: "/swapfile"

      AUTOUPDATE: true
      NODE_EXPORTER: true

    ubuntu_docker:
      ansible_host: 127.0.0.1

      ntp_service: "chrony"

      FIREWALL: true
      firewall_service: "ufw"

      SWAP: true
      swap_size: "512M"
      swap_file: "/swapfile"

      AUTOUPDATE: true
      DOCKER: true
      KOMODO: true
      NODE_EXPORTER: true

    wsl:
      ansible_host: 127.0.0.1

      AUDITD: false
      AUTOUPDATE: false
      DOCKER: false
      FAIL2BAN: false
      FIREWALL: false
      HOSTNAME: false
      LOGGING: false
      MAIL: false
      MONITORING: false
      NGINX: false
      NTP: false
      QEMU: false
      SSH: false
      SWAP: false
      USERS: true
      users_ansible_setup: false
      users_admin_setup: false
      users_root_setup: false
      VRRP: false

pbs_host_h:
  hosts:
    bk01:
      ansible_host: 127.0.0.1
      serverHostname: "bk01"

      NTP: true
      ntp_service: "chrony"

      PBS: true
      pbs_enterprise_repo: false
      pbs_interface_primary: "nic0"
      pbs_interface_secondary: ""

      NGINX: true

pmg_host_h:
  hosts:
    mx01:
      ansible_host: 127.0.0.1
      serverHostname: "mx01"

      NTP: true
      ntp_service: "chrony"

      PMG: true
      pmg_enterprise_repo: false
      pmg_interface_primary: "ens18"
      pmg_interface_secondary: ""

      NGINX: true

pve_host_h:
  hosts:
    vh01:
      ansible_host: 172.16.0.11
      serverHostname: "vh01"
      pve_interfaces:
        mgmt:
          ip: "172.16.0.11"
          cidr: "24"
          gw: "172.16.0.1"

  vars:
    NTP: true
    ntp_service: "chrony"

    PVE: true
    pve_enterprise_repo: false

    pve_interface_names:
      mgmt:
        primary: "enp26s0f0np0"

    NGINX: true

pve_cluster_h_mon:
  hosts:
    vh01:
      ansible_host: 172.16.0.21
      serverHostname: "vh01"
    vh02:
      ansible_host: 172.16.0.22
      serverHostname: "vh02"
    vh03:
      ansible_host: 172.16.0.23
      serverHostname: "vh03"
pve_cluster_h:
  hosts:
    vh01:
      ansible_host: 172.16.0.21
      serverHostname: "vh01"
      pve_interfaces:
        mgmt:
          ip: "172.16.0.21"
          cidr: "24"
          gw: "172.16.0.1"
        ceph:
          ip: "172.16.1.241"
          cidr: "28"
    vh02:
      ansible_host: 172.16.0.22
      serverHostname: "vh02"
      pve_interfaces:
        mgmt:
          ip: "172.16.0.22"
          cidr: "24"
          gw: "172.16.0.1"
        ceph:
          ip: "172.16.1.242"
          cidr: "28"
    vh03:
      ansible_host: 172.16.0.23
      serverHostname: "vh03"
      pve_interfaces:
        mgmt:
          ip: "172.16.0.23"
          cidr: "24"
          gw: "172.16.0.1"
        ceph:
          ip: "172.16.1.243"
          cidr: "28"

  vars:
    NTP: true
    ntp_service: "chrony"

    VRRP: true
    vrrp_service: "keepalived"
    vrrp_instance: "VI_1"
    vrrp_interface: "vmbr0"
    vrrp_router_id: 137
    vrrp_pass: "CHANGEME"
    vrrp_ip: "172.16.0.20"

    PVE: true
    pve_enterprise_repo: false
    pve_passthrough: false
    pve_cluster_switched: true
    pve_cluster_hostname: "vh"
    pve_cluster_FQDN: "vh.h.myah-mitchell.com"
    pve_group: "pve_cluster_h"
    pve_interface_names:
      ceph:
        primary: "ens2"
      mgmt:
        primary: "enp6s0"
        secondary: "enp7s0"

    pve_cluster_ha_groups:
      - name: AllNodes
        comment: "Group with All Nodes"
        nodes: "{{ groups[target] | join(',') }}"
        nofailback: false
        restricted: false

    pve_ceph_enabled: true
    pve_ceph_osds:
      - device: /dev/sdb
      - device: /dev/sdc
    pve_ceph_crush_rules:
      - name: replicated_rule
        type: host
    pve_ceph_pools:
      - name: ceph-vm
        pgs: 128
        rule: replicated_rule
        application: rbd
        autoscale_mode: "on"
        storage: true
        size: 3
        min_size: 2
        size_ratio: 80
    pve_ceph_fs:
      - name: ceph-fs
        pgs: 8
        rule: replicated_rule
        storage: true
    pve_ceph_mon_group: "pve_cluster_h_mon"
    pve_ceph_mgr_group: "pve_cluster_h_mon"
    pve_ceph_mds_group: "pve_cluster_h_mon"

    NGINX: true
